# -*- mode: ruby -*-
# vi: set ft=ruby :
BOX_IMAGE = "ubuntu/focal64"
DOMAIN = "aula104"
DNSIP = "192.168.56.100"

$dnsclient = <<-SHELL
  apt-get update
  systemctl disable --now systemd-resolved
  systemctl stop systemd-resolved
  echo -e "nameserver $1">/etc/resolv.conf
SHELL

$apacheserver = <<-SHELL
  apt-get update
  apt-get install -y apache2
  echo "<h1>Bienvenido a $1!</h1>">/var/www/html/index.html
SHELL

$nginxserver = <<-SHELL
  apt-get update
  apt-get install -y nginx
  echo "<h1>Bienvenido a $1!</h1>">/var/www/html/index.nginx-debian.html
SHELL

services = {
  "nginx"   => { :ip => "192.168.56.10", :provision=>$nginxserver, :port=> "8080" },
  "apache1" => { :ip => "192.168.56.11", :provision=>$apacheserver, :port=> "8081" },
  "apache2" => { :ip => "192.168.56.12", :provision=>$apacheserver, :port=> "8082" },
}

Vagrant.configure("2") do |config|
  # config general
  config.vm.box = BOX_IMAGE

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = 1024
    vb.customize ["modifyvm", :id, "--groups", "/DWEB"]
  end

  # dns 
  config.vm.define :dns do |guest|
    guest.vm.provider "virtualbox" do |vb, subconfig|
      vb.name = "dns"
      subconfig.vm.hostname = "dns.#{DOMAIN}"
      subconfig.vm.network :private_network, ip: DNSIP, virtualbox__intnet: "dnslab"
    end
    guest.vm.provision "shell", name: "dns-server", path: "enable-dnsmasq.sh", args: DNSIP
  end

  # services 
  services.each_with_index do |(hostname, info), idx|
    config.vm.define hostname do |guest|
      guest.vm.provider :virtualbox do |vb, subconfig|
        vb.name = hostname
        subconfig.vm.hostname = "#{hostname}.#{DOMAIN}"
        subconfig.vm.network :private_network, ip: info[:ip], virtualbox__intnet: "dnslab"
      end
      guest.vm.provision "shell", name: "dns-client \##{idx}", inline: $dnsclient, args: DNSIP
      guest.vm.provision "shell", name: "#{hostname}:#{info[:port]}", inline: info[:provision], args: hostname
      guest.vm.network "forwarded_port", guest: 80, host: info[:port]
    end 
  end
  
  # clients DHCP
  (1..2).each do |id|
    config.vm.define "client#{id}" do |guest|
      guest.vm.provider "virtualbox" do |vb, subconfig|
        vb.name = "client#{id}"
        subconfig.vm.hostname = "client#{id}.#{DOMAIN}"
        subconfig.vm.network :private_network, type: "dhcp", virtualbox__intnet: "dnslab"
      end
      guest.vm.provision "shell", name: "dns-client", inline: $dnsclient, args: DNSIP
      guest.vm.provision "shell", name: "testing", inline: <<-SHELL
        dig google.com +short
        dig -x 192.168.56.100 +short
        curl apache1 --no-progress-meter 
        curl apache2 --no-progress-meter 
        curl nginx --no-progress-meter 
      SHELL
    end
  end

end
