# -*- mode: ruby -*-
# vi: set ft=ruby :
BOX_SERVER = "ubuntu/focal64"
VBLAB = "test"
RED = "dchp"

Vagrant.configure("2") do |config|
  config.vm.box = BOX_SERVER

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = 1024
  end

  # # dns 
  # config.vm.define :fija do |guest|
  #   guest.vm.provider "virtualbox" do |vb, subconfig|
  #     vb.name = "fija"
  #     subconfig.vm.hostname = "fija"
  #     subconfig.vm.network :private_network, ip: "192.168.1.2",  virtualbox__intnet: VBLAB 
  #   end
  # end

  config.vm.define :dhcp do |guest|
    guest.vm.provider "virtualbox" do |vb, subconfig|
      vb.name = "dhcp"
      subconfig.vm.hostname = "dhcp"
      subconfig.vm.network :private_network, type: "dhcp" 
        end
  end
 
end
